version: 0.4.0.{build}

branches:
  only:
  - master
  - dev

image: Visual Studio 2015

configuration: Release

build_script:
- ps: ./build.ps1

test: off

deploy:
- provider: NuGet
  api_key:
    secure: tbaRea32KiHy+UjJoJ2DMj682qZYx84jwqRuQaSYkS3HJVr9FtjkoQe0REs2YVBm
  skip_symbols: false
  on:
    branch: master