version: 0.7.0.{build}

image: Visual Studio 2017

configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

build_script:
- ps: ./build.ps1

test: off

deploy:
- provider: NuGet
  api_key:
    secure: tbaRea32KiHy+UjJoJ2DMj682qZYx84jwqRuQaSYkS3HJVr9FtjkoQe0REs2YVBm
  skip_symbols: false
  on:
    branch: master